spring.application.name=HouZing

#local.dburl = mysql://localhost:3306/HouZing
#railway.dburl = mysql://root:eWqCkxaUiSGMoDJGbNTHlKbGDOhXvsAc@hayabusa.proxy.rlwy.net:15862/HouZing
#spring.datasource.url=jdbc:postgresql://neondb_owner:npg_rNi6dbRx4Bqw@ep-purple-lake-aofer4e5.c-2.ap-southeast-1.aws.neon.tech/neondb
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_rNi6dbRx4Bqw

spring.datasource.url=jdbc:postgresql://ep-purple-lake-aofer4e5.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rNi6dbRx4Bqw

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=admin123

jwt.secret=adfjlkaf93284u73jfdasf32fnno3afdh8734yfhnaoli8cny9483y7rhaon847ruhf08mcKrishna

#Pre Initialized Admin
manager.username = krishna
manager.password = pass